#!/usr/bin/php
<?php

	function compare($path1, $path2)
	{
			$fp_a = fopen($path1, 'rb');
			$fp_b = fopen($path2, 'rb');
			
			while (($b = fread($fp_a, 4096)) !== false)
			{
				$b_b = fread($fp_b, 4096);
				if ($b !== $b_b)
				{
					fclose($fp_a);
					fclose($fp_b);
					return false;
				}
			}
			
			fclose($fp_a);
			fclose($fp_b);
			return true;
	}




	$start_time = microtime($get_as_float=true);
	$path = $argv[1];  //path to directory

	//$Iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
	$Iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS));


	$MyDictionary = array();

	foreach ($Iterator as $file)
	{
		//$filesize = $file->getSize();  //filesize($file)
		
		if (in_array(filesize($file), array_keys($MyDictionary))) //Check filesize in dict keys
		{
			array_push($MyDictionary[filesize($file)], [$file]);
		}
		else  //If filesize not in dict keys
		{
			$MyDictionary[filesize($file)] = [[$file]];  //Add new key groups
		}
	}
	print_r($MyDictionary);
?>